import { parse } from '@fluent/syntax'

import { expectedKeysFromGcf } from './expected-keys'

/**
 * Generate or extend an ftl file with stubs for missing localization keys.
 * Existing keys are never modified — only new entries are appended.
 * Each stub has a TODO placeholder so `rifted pack` can catch unfilled strings.
 */
export function scaffoldFtl(opts: { gcf: object; existingFtl?: string; lang: string }): string {
	const { gcf, existingFtl, lang } = opts

	// parse existing keys so we don't duplicate them
	const existing = new Set<string>()
	if (existingFtl) {
		const ast = parse(existingFtl, {})
		for (const entry of ast.body) {
			if (entry.type !== 'Message') continue
			const id = (entry as any).id.name as string
			existing.add(id)
			for (const attr of (entry as any).attributes ?? []) {
				existing.add(`${id}.${attr.id.name}`)
			}
		}
	}

	const { required, optional } = expectedKeysFromGcf(gcf as any)
	const all = new Map([...required, ...optional])

	// group by message id so we emit one block per entity
	type Block = { msgId: string; hasValue: boolean; attrs: string[]; params: string[] }
	const blocks = new Map<string, Block>()

	// collect card param names for FTL variable hints
	const cardParams = new Map<string, string[]>()
	for (const card of (gcf as any).cards ?? []) {
		if (card.params) cardParams.set(cardKey(card.id), Object.keys(card.params))
	}

	for (const fullKey of all.keys()) {
		if (existing.has(fullKey)) continue
		const dot = fullKey.indexOf('.')
		const msgId = dot === -1 ? fullKey : fullKey.slice(0, dot)
		const attr = dot === -1 ? null : fullKey.slice(dot + 1)

		if (!blocks.has(msgId)) {
			blocks.set(msgId, { msgId, hasValue: false, attrs: [], params: cardParams.get(msgId) ?? [] })
		}
		const block = blocks.get(msgId)!
		if (attr === null) block.hasValue = true
		else block.attrs.push(attr)
	}

	if (blocks.size === 0) return existingFtl ?? ''

	const today = new Date().toISOString().slice(0, 10)
	const lines: string[] = []

	if (existingFtl && existingFtl.length > 0) {
		if (!existingFtl.endsWith('\n')) lines.push('')
		lines.push('')
		lines.push(`# auto-generated stubs (${today}, lang=${lang})`)
		lines.push('')
	} else {
		lines.push(`# auto-generated by rifted locales:scaffold (${today}, lang=${lang})`)
		lines.push('# fill in the TODO entries before packing')
		lines.push('')
	}

	const sorted = [...blocks.values()].sort((a, b) => (a.msgId < b.msgId ? -1 : 1))
	let lastKind: string | null = null

	for (const block of sorted) {
		const kind = kindFromKey(block.msgId)
		if (kind !== lastKind) {
			lines.push(`# -- ${kind} --`)
			lines.push('')
			lastKind = kind
		}

		// hint about available FTL variables for this entity
		if (block.params.length > 0) {
			lines.push(`# available variables: ${block.params.map(p => `{ $${p} }`).join('  ')}`)
		}

		if (block.hasValue) {
			lines.push(`${block.msgId} = TODO ${displayName(block.msgId)}`)
		} else {
			lines.push(`${block.msgId} =`)
		}

		for (const attr of block.attrs.sort()) {
			lines.push(`    .${attr} = TODO`)
		}
		lines.push('')
	}

	return (existingFtl ?? '') + lines.join('\n')
}

function cardKey(id: string): string {
	const colon = id.indexOf(':')
	if (colon === -1) return id
	const ns = id.slice(0, colon)
	const name = id.slice(colon + 1)
	return `${ns}-card-${name}`
}

// my_mod-card-rage → "card"
function kindFromKey(msgId: string): string {
	return msgId.split('-')[1] ?? 'misc'
}

// my_mod-card-rage → "Rage"
function displayName(msgId: string): string {
	const parts = msgId.split('-')
	const name = parts.slice(2).join(' ')
	if (!name) return msgId
	return name.charAt(0).toUpperCase() + name.slice(1)
}
