// typegen: a typed bridge to another mod from its public artifact. Reads a
// built gcf.json (or .rmod) and emits a TS module with qualified Refs, event
// handles (payload shapes scraped from emit ops) and state handles — so
// cross-namespace reuse gets autocomplete and rename safety without the
// other mod publishing its sources.

interface ScrapedEvent {
	name: string
	payloadKeys: Set<string>
}

interface Scraped {
	events: Map<string, ScrapedEvent>
	playerState: Set<string>
	teamState: Set<string>
	matchState: Set<string>
}

/** walk every array/object in the document looking for the ops that leak ids */
function scrape(doc: Record<string, unknown>, ns: string): Scraped {
	const out: Scraped = {
		events: new Map(),
		playerState: new Set(),
		teamState: new Set(),
		matchState: new Set(),
	}
	const prefix = `${ns}:`
	const own = (full: string) => (full.startsWith(prefix) ? full.slice(prefix.length) : null)

	const event = (full: unknown, payload?: unknown) => {
		if (typeof full !== 'string') return
		const name = own(full)
		if (name === null) return
		const e = out.events.get(name) ?? { name, payloadKeys: new Set<string>() }
		if (payload && typeof payload === 'object' && !Array.isArray(payload)) {
			for (const k of Object.keys(payload)) e.payloadKeys.add(k)
		}
		out.events.set(name, e)
	}

	const stateKey = (level: unknown, full: unknown) => {
		if (typeof full !== 'string') return
		const key = own(full)
		if (key === null) return
		if (level === 'player') out.playerState.add(key)
		else if (level === 'team') out.teamState.add(key)
		else if (level === 'match') out.matchState.add(key)
	}

	const visit = (node: unknown): void => {
		if (Array.isArray(node)) {
			const [head, a, b] = node
			if (head === 'emit') event(a, b)
			else if (head === 'add_state' || head === 'set_state') stateKey(a, b)
			else if (head === 'spend_player_state') stateKey('player', a)
			for (const item of node) visit(item)
			return
		}
		if (node && typeof node === 'object') {
			const obj = node as Record<string, unknown>
			// hooks subscribe to events too: { on: "ns:kind", ... }
			if (typeof obj.on === 'string' && obj.do !== undefined) event(obj.on)
			for (const v of Object.values(obj)) visit(v)
		}
	}
	visit(doc)
	return out
}

const SECTIONS = [
	['cards', 'card'],
	['modifiers', 'modifier'],
	['enemies', 'enemy'],
	['watchers', 'watcher'],
	['encounters', 'encounter'],
	['maps', 'map'],
	['affinities', 'affinity'],
] as const

/** ids are [a-z0-9_]+ but may start with a digit — quote those keys */
function tsKey(id: string): string {
	return /^[a-z_][a-z0-9_]*$/.test(id) ? id : `'${id}'`
}

export function generateRefsModule(doc: Record<string, unknown>, source: string): string {
	const ns = String(doc.namespace ?? '')
	if (!ns) throw new Error('document has no namespace')
	const version = typeof doc.version === 'number' ? doc.version : 1

	const lines: string[] = []
	const imports = new Set<string>(['type Ref'])

	lines.push(`// Generated by \`rifted typegen\` from ${source} — do not edit.`)
	lines.push(`// Typed bridge to the "${ns}" mod (document version ${version}).`)
	lines.push(`// Declare the dependency with:  requires: [<this module>]`)
	lines.push('')
	lines.push('__IMPORTS__')
	lines.push('')
	lines.push('// namespace + version make this module a ContentDependency:')
	lines.push("//   import * as dep from '...'; Pkg(ns, { requires: [dep] })")
	lines.push(`export const namespace = '${ns}'`)
	lines.push(`export const version = ${version}`)

	for (const [section, kind] of SECTIONS) {
		const entries = doc[section]
		if (!Array.isArray(entries) || entries.length === 0) continue
		lines.push('')
		lines.push(`export const ${section} = {`)
		for (const entry of entries as Array<{ id: string }>) {
			lines.push(`\t${tsKey(entry.id)}: { kind: '${kind}', id: '${ns}:${entry.id}' },`)
		}
		lines.push(`} as const satisfies Record<string, Ref<'${kind}'>>`)
	}

	const scraped = scrape(doc, ns)

	if (scraped.events.size > 0) {
		imports.add('EventHandle')
		lines.push('')
		lines.push('export const events = {')
		for (const e of [...scraped.events.values()].sort((a, b) => a.name.localeCompare(b.name))) {
			const shape =
				e.payloadKeys.size > 0
					? `<{ ${[...e.payloadKeys]
							.sort()
							.map(k => `${k}: number`)
							.join('; ')} }>`
					: ''
			lines.push(`\t${tsKey(e.name)}: new EventHandle${shape}('${ns}:${e.name}'),`)
		}
		lines.push('}')
	}

	const stateBlock = (
		name: string,
		keys: Set<string>,
		make: (key: string, full: string) => string,
	) => {
		if (keys.size === 0) return
		lines.push('')
		lines.push(`export const ${name} = {`)
		for (const key of [...keys].sort()) {
			lines.push(`\t${tsKey(key)}: ${make(key, `${ns}:${key}`)},`)
		}
		lines.push('}')
	}

	if (scraped.playerState.size > 0) imports.add('PlayerStateHandle')
	if (scraped.teamState.size > 0 || scraped.matchState.size > 0) imports.add('StateEntry')
	stateBlock('playerState', scraped.playerState, (_k, full) => `new PlayerStateHandle('${full}')`)
	stateBlock(
		'teamState',
		scraped.teamState,
		(_k, full) => `new StateEntry('team.state.${full}', 'team', '${full}')`,
	)
	stateBlock(
		'matchState',
		scraped.matchState,
		(_k, full) => `new StateEntry('match.state.${full}', 'match', '${full}')`,
	)

	const importLine = `import { ${[...imports].sort().join(', ')} } from '@rifted/sdk'`
	return `${lines.join('\n').replace('__IMPORTS__', importLine)}\n`
}

/** the document version exposed by a built document */
export function docVersion(doc: Record<string, unknown>): number {
	return typeof doc.version === 'number' ? doc.version : 1
}

export interface PackageOptions {
	/** npm package name (default "@<namespace>/types") */
	name?: string
	/** npm semver (default "<docVersion>.0.0") */
	version?: string
	/** peer range for @rifted/sdk (default "^1.0.0") */
	sdkRange?: string
}

/**
 * a publishable typed-bridge package: the typegen module plus a manifest.
 * @rifted/sdk is a peerDependency on purpose — the bridge constructs
 * EventHandle/StateEntry instances that the consumer's `on()`/`requires`
 * check with instanceof, so both sides must share one SDK instance.
 */
export function generatePackage(
	doc: Record<string, unknown>,
	source: string,
	opts: PackageOptions = {},
): Record<string, string> {
	const ns = String(doc.namespace ?? '')
	if (!ns) throw new Error('document has no namespace')
	const name = opts.name ?? `@${ns}/types`
	const version = opts.version ?? `${docVersion(doc)}.0.0`
	const sdkRange = opts.sdkRange ?? '^1.0.0'

	const manifest = {
		name,
		version,
		description: `Typed bridge to the "${ns}" Rifted mod`,
		type: 'module',
		exports: { '.': { types: './index.ts', import: './index.ts' } },
		files: ['index.ts'],
		// peer, not a dependency: one shared @rifted/sdk instance (instanceof)
		peerDependencies: { '@rifted/sdk': sdkRange },
		keywords: ['rifted', 'rifted-mod', ns],
		license: 'MIT',
	}

	const readme = [
		`# ${name}`,
		'',
		`Typed bridge to the \`${ns}\` Rifted mod — generated by \`rifted typegen\`.`,
		'',
		'```ts',
		`import * as ${ns} from '${name}'`,
		'',
		`const pkg = Pkg('mymod', { requires: [${ns}] })   // version tracks the installed package`,
		`pkg.card('zealot', { affinity: ${ns}.affinities.berserk, /* ... */ })`,
		'```',
		'',
	].join('\n')

	return {
		'index.ts': generateRefsModule(doc, source),
		'package.json': `${JSON.stringify(manifest, null, '\t')}\n`,
		'README.md': readme,
	}
}
